# Generated by Django 2.2.13 on 2021-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=6, unique=True)),
                ('num_code', models.CharField(max_length=10)),
                ('char_code', models.CharField(max_length=4)),
                ('nominal', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('previous', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
